# Generated by Django 5.1.5 on 2025-05-12 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('previous_day_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('previous_week_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('previous_month_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('all_time_high_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('all_time_high_date', models.DateField(blank=True, null=True)),
                ('all_time_low_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('all_time_low_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volatility_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('volatility_90d', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('value_at_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('concentration_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='assets.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('chain', models.CharField(max_length=50)),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price_usd', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('price_updated_at', models.DateTimeField(auto_now=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'chain', 'contract_address')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=255)),
                ('block_number', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('gas_price', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('gas_used', models.PositiveBigIntegerField(default=0)),
                ('transaction_fee', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('transaction_type', models.CharField(choices=[('receive', 'Receive'), ('send', 'Send'), ('swap', 'Swap'), ('liquidity', 'Liquidity'), ('stake', 'Stake'), ('unstake', 'Unstake'), ('earn', 'Earn Rewards'), ('fee', 'Fee'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=18, max_digits=36)),
                ('value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.token')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transfers', to='assets.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='WalletToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, max_digits=36)),
                ('balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assets.portfolio')),
            ],
            options={
                'indexes': [models.Index(fields=['portfolio', 'timestamp'], name='assets_port_portfol_e53438_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=12, max_digits=24)),
                ('timestamp', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='assets.token')),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'timestamp'], name='assets_toke_token_i_f6f354_idx')],
                'unique_together': {('token', 'timestamp')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'timestamp'], name='assets_tran_wallet__b1c89b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('wallet', 'transaction_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='wallettoken',
            unique_together={('wallet', 'token')},
        ),
    ]
